Update workspace.yml

diff --git a/.github/workflows/workflows.yml b/.github/workflows/workflows.yml
--- a/.github/workflows/workflows.yml
+++ b/.github/workflows/workflows.yml
@@ -1,7 +1,8 @@
 name: Main Workflow
 on:
   push:
-    branches: [ master ]
+    branches-ignore:
+      - master
 
 jobs:
 #  lint: 
@@ -29,3 +30,71 @@ jobs:
         uses: actions/checkout@v2
       - name: Run Yelp's detect-secrets
         uses: RobertFischer/detect-secrets-action@v2.0.0
+
+jobs:
+  set-env:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Set environment variables
+        run: |
+          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
+          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
+      - name: Use environment variables
+        run: |
+          echo "GIT_SHA=${GIT_SHA}"
+          echo "GIT_BRANCH=${GIT_BRANCH}"
+          #  set-workspace-and-deploy:
+          #    runs-on: 'ubuntu-latest'
+          #    steps:
+          #      - name: Checkout
+          #        uses: actions/checkout@v2
+          #
+          #      - name: Install tarraform
+          #        uses: hashicorp/setup-terraform@v1.2.1
+          #
+          #      - name: Terraform Init
+          #        id: init
+          #        run: terraform init
+          #
+          #      - name: setup workspace
+          #        id: workspace
+          #        run: terraform workspace ${GITHUB_REF##*/}
+          #
+
+        #  deploy:
+        #    runs-on: ubuntu-latest
+        #    env:
+        #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        #
+        #    steps:
+        #    - uses: actions/checkout@main
+        #    - uses: hashicorp/setup-terraform@v1.2.1
+        #
+        #    - name: Terraform fmt
+        #      id: fmt
+        #      run: terraform fmt -check
+        #      continue-on-error: true
+        #
+        #    - name: Terraform Init
+        #      id: init
+        #      run: terraform init
+        #
+        #    - name: Terraform Validate
+        #      id: validate
+        #      run: terraform validate
+        #
+        #    - name: Terraform Plan
+        #      id: plan
+        #      run: terraform plan
+        #
+        #    - name: Terraform Plan Status
+        #      if: steps.plan.outcome == 'failure'
+        #      run: exit 1
+        #
+        #    - name: Terraform Apply
+        #      run: terraform apply -auto-approve
+        #
